package uni.aed.gui;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import uni.aed.Biblioteca.LibraryToGUI;

public class FrmBiblioteca extends javax.swing.JFrame {
    private final DefaultListModel modeloList1 = new DefaultListModel();
    private final DefaultListModel modeloList2 = new DefaultListModel();
    private LibraryToGUI library = new LibraryToGUI();
    private int accion;
    
    public FrmBiblioteca() {
        initComponents();
        listaLibros.setModel(modeloList1);
        listaUsuarios.setModel(modeloList2);
        lblAgregar.setVisible(false);
        lblPrestamo.setVisible(false);
        lblDevolucion.setVisible(false);
        txtUsuario.setEditable(false);
        txtLibro.setEditable(false);
        txtAutor.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        btnPrestamo = new javax.swing.JButton();
        btnDevolucion = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnStatus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaLibros = new javax.swing.JList<>();
        txtAutor = new javax.swing.JTextField();
        lblAutor = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        txtLibro = new javax.swing.JTextField();
        lblLibro = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaUsuarios = new javax.swing.JList<>();
        lblAgregar = new javax.swing.JLabel();
        lblPrestamo = new javax.swing.JLabel();
        lblDevolucion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregar.setText("Agregar libro");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnPrestamo.setText("Registrar prestamo");
        btnPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamoActionPerformed(evt);
            }
        });

        btnDevolucion.setText("Registrar devolucion");
        btnDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucionActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        lblTitulo.setText("BIBLIOTECA");

        btnStatus.setText("Status");
        btnStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listaLibros);

        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });

        lblAutor.setText("Nombre del autor: ");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        lblUsuario.setText("Nombre del usuario: ");

        txtLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibroActionPerformed(evt);
            }
        });

        lblLibro.setText("Titulo del libro:");

        jScrollPane2.setViewportView(listaUsuarios);

        lblAgregar.setText("Ingresar datos del libro");

        lblPrestamo.setText("Ingresar datos del prestamo");

        lblDevolucion.setText("Ingresar datos de la devolucion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(lblPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(lblDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAutor)
                                    .addComponent(lblLibro))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAceptar)
                                    .addComponent(txtLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 105, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(lblTitulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrestamo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDevolucion, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuario)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(lblAgregar)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAutor)
                            .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLibro)))
                .addGap(36, 36, 36)
                .addComponent(btnAceptar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrestamo)
                        .addGap(18, 18, 18)
                        .addComponent(btnDevolucion)
                        .addGap(18, 18, 18)
                        .addComponent(btnStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
       //usamos 3 varibales String para cada nombre que necesitamos
        String nomAutor, nomUsuario, titLibro;
        //para verificar la existencia de un libro o un autor 
        int verifica;
                
        switch(accion){
            
            case 1 -> {//caso 1
                //obtenemos los valores de nuestras variables de los TextField
                nomAutor = txtAutor.getText();
                titLibro= txtLibro.getText();
                //Nos aseguramos de poner su primera letra en mayuscula
                nomAutor = nomAutor.substring(0,1).toUpperCase() + nomAutor.substring(1);
                titLibro = titLibro.substring(0,1).toUpperCase() + titLibro.substring(1);
                //usamos el metodo include Book modificado enviandole nuestras dos varibales
                library.includeBook( nomAutor,  titLibro);
            }
                
            
            case 2 -> {//caso 2 
                //obtenemos los valores de nuestras variables de los TextField
                nomUsuario = txtUsuario.getText();
                nomAutor = txtAutor.getText();
                titLibro= txtLibro.getText();
              
                //Nos aseguramos de poner sus primeras letras en mayuscula
     
                nomAutor = nomAutor.substring(0,1).toUpperCase() + nomAutor.substring(1);
                titLibro = titLibro.substring(0,1).toUpperCase() + titLibro.substring(1);
                nomUsuario = nomUsuario.substring(0,1).toUpperCase() + nomUsuario.substring(1);
                
                //verifica obtiene el retorno del metodo checkOutBook modificado 
                verifica = library.checkOutBook(nomAutor, nomUsuario, titLibro);
                
                if(verifica == -1)//retorna -1 cuando el autor no se encuentra
                    JOptionPane.showMessageDialog(this,"Verifique el nombre del autor ",
                            "WARNING",JOptionPane.WARNING_MESSAGE);//arrojamos una advertencia
                if(verifica == -2)//retorna -2 cuando el libro no se encuentra
                    JOptionPane.showMessageDialog(this,"Verifique el titulo del libro",
                            "WARNING",JOptionPane.WARNING_MESSAGE);//arrojamos una advertencia
            }
                
            case 3 -> { //caso 3
                //obtenemos los valores de nuestras variables de los TextField
                nomUsuario = txtUsuario.getText();
                nomAutor = txtAutor.getText();
                titLibro= txtLibro.getText();
                
                //Nos aseguramos de poner sus primeras letras en mayuscula
                nomAutor = nomAutor.substring(0,1).toUpperCase() + nomAutor.substring(1);
                titLibro = titLibro.substring(0,1).toUpperCase() + titLibro.substring(1);
                nomUsuario = nomUsuario.substring(0,1).toUpperCase() + nomUsuario.substring(1);
                
                //verifica obtiene el retorno del metodo returnBook modificado
                verifica = library.returnBook(nomAutor, nomUsuario, titLibro);
                
                if(verifica == -1)//retorna -1 cuando el usuario no se encuentra
                    JOptionPane.showMessageDialog(this,"Verifique el nombre del usuario ",
                            "WARNING",JOptionPane.WARNING_MESSAGE);//arrojamos una advertencia
                if(verifica == -2)//retorna -2 cuando el autor no se encuentra
                    JOptionPane.showMessageDialog(this,"Verifique el nombre del autor",
                            "WARNING",JOptionPane.WARNING_MESSAGE);//arrojamos una advertencia
                if(verifica == -3)//retorna -3 cuando el libro no se encuentra
                    JOptionPane.showMessageDialog(this,"Verifique el titulo del libro",
                            "WARNING",JOptionPane.WARNING_MESSAGE);//arrojamos una advertencia
            }
        }
        
        //limpiamos los TxtFields
        txtAutor.setText("");
        txtLibro.setText("");
        txtUsuario.setText("");
        
    }//GEN-LAST:event_btnAceptarActionPerformed
    
    private void btnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusActionPerformed
       //limpiamos las dos listas
        modeloList1.clear();
        modeloList2.clear();

        //cadena sera el string que escribiremos en cada lista
        String cadena;
        
        for (int i = (int) 'A'; i <= (int) 'Z'; i++){
            //hacemos un for e iteramos por cada letra
            
            //el metodo statusBooks nos devuelve un String para esta letra
            cadena = library.statusBooks(i);
            
            if (cadena != null){//existe el caso en el que la lista esta vacia, entonces verificamos que cadena no sea null
                modeloList1.addElement(cadena);//añadimos la cadena a la lista 
                modeloList1.addElement("");//y aumentamos un salto de linea
            }
            
        }
        
        //hacemos un for e iteramos por cada letra
        for (int i = (int) 'A'; i <= (int) 'Z'; i++){
            //el metodo statusPatrons nos devuelve un String para esta letra
            cadena = library.statusPatrons(i);
            
            if (cadena != null){//existe el caso en el que la lista esta vacia, entonces verificamos que cadena no sea null
                modeloList2.addElement(cadena);//añadimos la cadena a la lista
                modeloList2.addElement("");//y aumentamos un salto de linea
            }
            
        }
            
    }//GEN-LAST:event_btnStatusActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucionActionPerformed
        //adecuamos para que el usuario pueda devolver un libro
        //hacemos que todos los TxtField sean editables
        txtUsuario.setEditable(true); 
        txtLibro.setEditable(true);
        txtAutor.setEditable(true);
        //hacemos visible la etiqueta que le corresponde a esta operacion e invisivilisamos las otras
        lblAgregar.setVisible(false);
        lblPrestamo.setVisible(false);
        lblDevolucion.setVisible(true);
        
        accion = 3; //accion para el switch de btnAceptar
    }//GEN-LAST:event_btnDevolucionActionPerformed

    private void btnPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamoActionPerformed
        //adecuamos para que el usuario pueda prestar un libro
        //hacemos que todos los TxtField sean editables
        txtUsuario.setEditable(true);
        txtLibro.setEditable(true);
        txtAutor.setEditable(true);
        //hacemos visible la etiqueta que le corresponde a esta operacion e invisivilisamos las otras
        lblAgregar.setVisible(false);
        lblPrestamo.setVisible(true);
        lblDevolucion.setVisible(false);
        
        accion =2;//accion para el switch de btnAceptar
    }//GEN-LAST:event_btnPrestamoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        //adecuamos para que el usuario pueda agregar un libro
        //hacemos que todos los TxtField sean editables excepto txtUsuario porque no lo necesitamos
        txtUsuario.setEditable(false);
        txtLibro.setEditable(true);
        txtAutor.setEditable(true);
        //hacemos visible la etiqueta que le corresponde a esta operacion e invisivilisamos las otras
        lblAgregar.setVisible(true);
        lblPrestamo.setVisible(false);
        lblDevolucion.setVisible(false);
        
        accion =1;//accion para el switch de btnAceptar
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_txtAutorActionPerformed

    private void txtLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibroActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBiblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnDevolucion;
    private javax.swing.JButton btnPrestamo;
    private javax.swing.JButton btnStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblDevolucion;
    private javax.swing.JLabel lblLibro;
    private javax.swing.JLabel lblPrestamo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JList<String> listaLibros;
    private javax.swing.JList<String> listaUsuarios;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtLibro;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
